# Generated by Django 5.2.8 on 2025-11-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingrequest",
            name="basic_context",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="meetingrequest",
            name="goals",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="meetingrequest",
            name="pain_points",
            field=models.TextField(blank=True),
        ),
    ]
