# Generated by Django 5.2.8 on 2025-12-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_meetingrequest_basic_context_meetingrequest_goals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='owner_org',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='owner_user',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='event',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='requester',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MeetingRequest',
        ),
    ]
