# Generated by Django 5.2.8 on 2025-11-28 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="activity",
            old_name="description",
            new_name="message",
        ),
        migrations.AddField(
            model_name="activity",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["-created_at"], name="client_acti_created_21c995_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["user"], name="client_acti_user_id_5bb81b_idx"),
        ),
    ]
