# Generated by Django 5.2.8 on 2025-11-28 17:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_alter_activity_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("malta", "Malta"),
                            ("eu_non_malta", "EU (non-Malta)"),
                            ("non_eu", "Non-EU"),
                            ("other", "Other (specify)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("jurisdiction_other", models.CharField(blank=True, max_length=100)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("mt", "Maltese"),
                            ("it", "Italian"),
                            ("other", "Other (specify)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("language_other", models.CharField(blank=True, max_length=100)),
                (
                    "keyboard_layout",
                    models.CharField(
                        choices=[
                            ("en_us", "EN-US"),
                            ("en_uk", "EN-UK"),
                            ("mt", "MT"),
                            ("it", "IT"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("keyboard_other", models.CharField(blank=True, max_length=100)),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("dd_mm_yyyy", "DD/MM/YYYY"),
                            ("mm_dd_yyyy", "MM/DD/YYYY"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time_format_24h", models.BooleanField(default=True)),
                ("accepted_service_agreement", models.BooleanField(default=False)),
                ("portal_interests", models.JSONField(default=list)),
                ("portal_interests_other", models.TextField(blank=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("founder", "Founder / Entrepreneur"),
                            ("small_business", "Small business owner"),
                            ("corporate", "Corporate representative"),
                            ("public_ngo", "Public sector / NGO"),
                            ("academic", "Researcher / Academic"),
                            ("professional", "Individual professional"),
                            ("other", "Other (specify)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("user_type_other", models.CharField(blank=True, max_length=100)),
                (
                    "project_stage",
                    models.CharField(
                        choices=[
                            ("exploration", "Early Exploration"),
                            ("pre_startup", "Pre-Startup / Planning"),
                            ("operational", "Operational but seeking optimisation"),
                            ("scaling", "Scaling / Growth"),
                            ("unsure", "Unsure"),
                        ],
                        max_length=50,
                    ),
                ),
                ("orr_pillars", models.JSONField(default=list)),
                (
                    "has_active_project",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("maybe", "Maybe")],
                        max_length=10,
                    ),
                ),
                (
                    "project_description",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("challenges", models.JSONField(default=list)),
                ("challenges_other", models.TextField(blank=True)),
                (
                    "meeting_format",
                    models.CharField(
                        choices=[
                            ("video", "Online (video)"),
                            ("phone", "Phone call"),
                            ("in_person", "In-person (subject to availability)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "communication_tone",
                    models.CharField(
                        choices=[
                            ("concise", "Concise and direct"),
                            ("detailed", "Detailed and explanatory"),
                            ("technical", "Technical"),
                            ("non_technical", "Non-technical"),
                            ("no_preference", "No preference"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notification_preference",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("portal_only", "In-portal notifications only"),
                            ("both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ai_specialist_domains", models.JSONField(default=list)),
                ("ai_specialist_other", models.TextField(blank=True)),
                ("additional_context", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Questionnaire",
                "verbose_name_plural": "Onboarding Questionnaires",
            },
        ),
    ]
