# Generated by Django 5.2.8 on 2025-12-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_favoritedocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
