# Generated by Django 5.2.8 on 2026-04-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_favoritedocument_updated_at_project_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
