FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# Add Poetry to PATH
ENV PATH="/root/.local/bin:$PATH"

COPY pyproject.toml poetry.lock* /app/


RUN poetry install --no-root

COPY manage.py /app/manage.py
COPY wait-for-it.sh /app/wait-for-it.sh
COPY entrypoint.dev.sh /app/entrypoint.dev.sh


RUN chmod +x /app/entrypoint.dev.sh

# Expose port
EXPOSE 8000



CMD ["bash", "-c", "echo 'Django container — no command provided'"]