FROM python:3.12-slim

# Set working directory
WORKDIR /app

ENV PYTHONPATH=/app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV POETRY_VIRTUALENVS_CREATE=false

RUN mkdir -p /app/logs

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*


# Install Stripe CLI
RUN curl -sSL https://github.com/stripe/stripe-cli/releases/download/v1.10.0/stripe_1.10.0_linux_x86_64.tar.gz -o stripe-cli.tar.gz \
    && tar -xvzf stripe-cli.tar.gz \
    && mv stripe /usr/local/bin/stripe \
    && rm stripe-cli.tar.gz



# Install Poetry
RUN apt-get update && apt-get install -y python3-pip python3-venv build-essential libpq-dev curl \
    && python3 -m pip install --upgrade pip \
    && pip install poetry



COPY pyproject.toml poetry.lock* /app/


RUN poetry install --no-root

ENV PATH="/app/.venv/bin:$PATH"

COPY . /app


RUN chmod +x /app/entrypoint.dev.sh

# Expose port
EXPOSE 8000



CMD ["bash", "-c", "echo 'Starting Django and Stripe CLI...' && ./entrypoint.dev.sh"]