FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*


# Install Stripe CLI
RUN curl -sSL https://github.com/stripe/stripe-cli/releases/download/v1.10.0/stripe_1.10.0_linux_x86_64.tar.gz -o stripe-cli.tar.gz \
    && tar -xvzf stripe-cli.tar.gz \
    && mv stripe /usr/local/bin/stripe \
    && rm stripe-cli.tar.gz

# Install Poetry
RUN apt-get update && apt-get install -y python3-pip python3-venv build-essential libpq-dev curl \
    && python3 -m pip install --upgrade pip \
    && pip install poetry
    
# Add Poetry to PATH
ENV PATH="/root/.local/bin:$PATH"

COPY pyproject.toml poetry.lock* /app/


RUN poetry install --no-root

COPY manage.py /app/manage.py
COPY wait-for-it.sh /app/wait-for-it.sh
COPY entrypoint.dev.sh /app/entrypoint.dev.sh


RUN chmod +x /app/entrypoint.dev.sh

# Expose port
EXPOSE 8000



CMD ["bash", "-c", "echo 'Starting Django and Stripe CLI...' && ./entrypoint.dev.sh"]