# Generated by Django 5.2.8 on 2025-12-09 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingplan",
            name="billing_type",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("metered", "Per Hour / Metered")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.pricingplan",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="used_hours",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
