# Generated by Django 5.2.8 on 2025-12-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_stripecustomer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripe_card_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
