# Generated by Django 5.2.8 on 2025-12-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_stripeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='has_valid_payment_method',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='last_payment_failed',
            field=models.BooleanField(default=False),
        ),
    ]
