# Generated by Django 5.2.8 on 2025-11-18 19:39

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsCaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Analytics Case Studies", max_length=200),
                ),
                ("active_users", models.IntegerField(default=2780)),
                ("questions_answered", models.IntegerField(default=3298)),
                ("avg_session_length", models.DurationField(default="00:02:34")),
                (
                    "starting_knowledge",
                    models.DecimalField(decimal_places=2, default=64.0, max_digits=5),
                ),
                (
                    "current_knowledge",
                    models.DecimalField(decimal_places=2, default=86.0, max_digits=5),
                ),
                (
                    "knowledge_gain",
                    models.DecimalField(decimal_places=2, default=0.34, max_digits=5),
                ),
                ("monthly_activity", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("excerpt", models.TextField(blank=True)),
                ("content", models.TextField()),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="blogs/"),
                ),
                ("category", models.CharField()),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="IndustryInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        default="Industry Specific Insights", max_length=200
                    ),
                ),
                ("real_time_users", models.PositiveIntegerField(default=60700)),
                ("total_visits", models.PositiveIntegerField(default=40200)),
                (
                    "visit_duration",
                    models.DurationField(
                        default=datetime.timedelta(days=1, seconds=46320)
                    ),
                ),
                ("top_countries", models.JSONField(default=list)),
                ("engagement_data", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
