# Generated by Django 4.2.7 on 2025-12-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_contactinfo_faq_servicecard_sitesettings_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Supporting Copy', max_length=200)),
                ('paragraph_1', models.TextField(default='Just like a skilled general practitioner, we start from your story not our framework. We take time to understand how your business really works before prescribing anything.')),
                ('paragraph_2', models.TextField(default="We're not a lone consultant — we're a central coordination layer with a distributed network behind it. When needed, we draw on specialists across continents, but you always deal with one point of contact: ORR, focused on what's best for you.")),
                ('paragraph_3', models.TextField(default="We fix what's slowing you down, strengthen systems around how your people actually work, and when deeper input is needed, we bring it in at the right moment — always in service of your goals.")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Approach Section',
                'verbose_name_plural': 'Approach Section',
            },
        ),
        migrations.CreateModel(
            name='BusinessSystemCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_systems/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Business System Card',
                'verbose_name_plural': 'Business System Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSystemSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Businesses as a Living System', max_length=200)),
                ('subtitle', models.CharField(default='Think of your organisation like a body', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Business System Section',
                'verbose_name_plural': 'Business System Section',
            },
        ),
        migrations.CreateModel(
            name='MessageStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Message Strip', max_length=200)),
                ('message', models.TextField(default="Businesses thrive like living organisms when all their systems work together *around real human needs*. ORR keeps your 'business physiology' in peak condition — aligning operations, communication, cash flow, compliance, data, and projects around the people you serve")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Message Strip',
                'verbose_name_plural': 'Message Strip',
            },
        ),
        migrations.CreateModel(
            name='ORRReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='What you Get: The ORR Report', max_length=200)),
                ('subtitle', models.TextField(default='After your first meeting, you receive a decision-ready ORR report designed to be immediately useful inside your organisation.')),
                ('feature_1', models.TextField(default='explain your situation in your language,')),
                ('feature_2', models.TextField(default='highlights key issues and risks that affect your customers and teams')),
                ('feature_3', models.TextField(default='proposes quick fixes and longer-term improvements that respect your constraints')),
                ('feature_4', models.TextField(default='shows where advisory, digital systems/AI, or living-systems work will have most impact')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ORR Report Section',
                'verbose_name_plural': 'ORR Report Section',
            },
        ),
        migrations.CreateModel(
            name='ORRRoleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default="ORR's Role", max_length=200)),
                ('description', models.TextField(default='We act like specialist doctors for your business physiology - but we start from your symptoms and your priorities. We check the health of your system, diagnosis issues, and co-design solutions that your people can actually use, keeping everything working together over time.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ORR Role Section',
                'verbose_name_plural': 'ORR Role Section',
            },
        ),
        migrations.CreateModel(
            name='ProcessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='How we work: Five Stages', max_length=200)),
                ('subtitle', models.CharField(default='Every stage is built around you – your pace, your risk appetite, your resources', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Process Section',
                'verbose_name_plural': 'Process Section',
            },
        ),
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Process Stage',
                'verbose_name_plural': 'Process Stages',
                'ordering': ['order'],
            },
        ),
    ]
