# Generated by Django 4.2.7 on 2025-12-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_approachsection_businesssystemcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_1_description',
            field=models.TextField(default='Communication, data flow, and decision-making pathways'),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_1_image',
            field=models.CharField(default='/images/nervous_system.png', max_length=500),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_1_title',
            field=models.CharField(default='Nervous System', max_length=100),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_2_description',
            field=models.TextField(default='Cash flow, resource distribution, and value exchange'),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_2_image',
            field=models.CharField(default='/images/circulatory_system.png', max_length=500),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_2_title',
            field=models.CharField(default='Circulatory System', max_length=100),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_3_description',
            field=models.TextField(default='Risk management, compliance, and protective measures'),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_3_image',
            field=models.CharField(default='/images/immune_system.png', max_length=500),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_3_title',
            field=models.CharField(default='Immune System', max_length=100),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_1_image',
            field=models.CharField(default='/images/report_feature_1.png', max_length=500),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_2_image',
            field=models.CharField(default='/images/report_feature_2.png', max_length=500),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_3_image',
            field=models.CharField(default='/images/report_feature_3.png', max_length=500),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_4_image',
            field=models.CharField(default='/images/report_feature_4.png', max_length=500),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='main_image',
            field=models.CharField(default='/images/orr_report_main.png', max_length=500),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_1_description',
            field=models.TextField(default='We start by understanding your current situation'),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_1_title',
            field=models.CharField(default='Listen', max_length=100),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_2_description',
            field=models.TextField(default='Identify key issues and opportunities'),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_2_title',
            field=models.CharField(default='Diagnose', max_length=100),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_3_description',
            field=models.TextField(default='Co-create solutions that fit your context'),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_3_title',
            field=models.CharField(default='Design', max_length=100),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_4_description',
            field=models.TextField(default='Execute changes with your team'),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_4_title',
            field=models.CharField(default='Implement', max_length=100),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_5_description',
            field=models.TextField(default='Ensure lasting impact and continuous improvement'),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_5_title',
            field=models.CharField(default='Sustain', max_length=100),
        ),
    ]
