# Generated by Django 4.2.7 on 2025-12-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_comprehensive_cms_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HowWeOperatePage',
            new_name='HowWeOperatePageContent',
        ),
    ]
