# Generated by Django 4.2.7 on 2025-12-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_businesssystemsection_card_1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services_glow_image',
            field=models.CharField(default='/images/glowww.png', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_title',
            field=models.CharField(default='Strategic Advisory & Compliance', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_description',
            field=models.TextField(default='Regulatory clarity, ESG and sustainability frameworks, biotechnology and environmental questions - distilled into simple, usable direction for your organisation.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_button',
            field=models.CharField(default='Explore Strategic Advisory & Compliance', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_title',
            field=models.CharField(default='Digital Systems, Automation & AI', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_description',
            field=models.TextField(default='SOPs, workflows, portals, dashboards, and AI-assisted tools designed around your team\'s habits, constraints and growth plans'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_button',
            field=models.CharField(default='Explore Digital Systems, Automation & AI', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_title',
            field=models.CharField(default='Living Systems & Regeneration', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_description',
            field=models.TextField(default='Support for land, water, species, and ecosystems - tailored to your sites your risks, and your opportunities'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_button',
            field=models.CharField(default='Explore Living Systems & Regeneration', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(default='Quick Service Snapshot - 3 Pillars', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_subtitle',
            field=models.TextField(default='All three pillars are shaped around your context - no generic playbooks'),
        ),
    ]
