# Generated by Django 4.2.7 on 2026-01-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_fix_content_card_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcard',
            options={'ordering': ['order'], 'verbose_name': 'Content Card', 'verbose_name_plural': 'Content Cards'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email_address',
            field=models.EmailField(default='demo@gmail.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone_number',
            field=models.CharField(default='+012 3456 789', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='email_address',
            field=models.EmailField(default='demo@gmail.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='phone_number',
            field=models.CharField(default='+012 3456 789', max_length=500),
        ),
        migrations.AlterField(
            model_name='contentcard',
            name='card_slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contentcard',
            name='image_url',
            field=models.URLField(default='https://res.cloudinary.com/depeqzb6z/image/upload/v1765559589/21743692_6495306_uay57y.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('services', 'Services'), ('pricing', 'Pricing'), ('process', 'Process'), ('support', 'Support')], default='general', max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_email',
            field=models.EmailField(default='info@orr.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.URLField(default='/contact', max_length=500),
        ),
        migrations.AlterField(
            model_name='legacypolicypage',
            name='policy_item_1_number',
            field=models.CharField(default='01', max_length=500),
        ),
        migrations.AlterField(
            model_name='legacypolicypage',
            name='policy_item_2_number',
            field=models.CharField(default='02', max_length=500),
        ),
        migrations.AlterField(
            model_name='legacypolicypage',
            name='policy_item_3_number',
            field=models.CharField(default='03', max_length=500),
        ),
        migrations.AlterField(
            model_name='livingsystemspagecontent',
            name='hero_image',
            field=models.URLField(default='https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop', max_length=500),
        ),
        migrations.AlterField(
            model_name='operationalsystemspagecontent',
            name='hero_image',
            field=models.URLField(default='https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop', max_length=500),
        ),
        migrations.AlterField(
            model_name='policyitem',
            name='number',
            field=models.CharField(default='01', max_length=500),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='image_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=600&fit=crop', max_length=500),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='step_number',
            field=models.CharField(default='01', max_length=500),
        ),
        migrations.AlterField(
            model_name='resourcesblogspage',
            name='tip_1_number',
            field=models.CharField(default='01', max_length=500),
        ),
        migrations.AlterField(
            model_name='resourcesblogspage',
            name='tip_2_number',
            field=models.CharField(default='02', max_length=500),
        ),
        migrations.AlterField(
            model_name='resourcesblogspage',
            name='tip_3_number',
            field=models.CharField(default='03', max_length=500),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='icon',
            field=models.CharField(help_text='CSS icon class or emoji', max_length=500),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='pillar',
            field=models.CharField(choices=[('strategic', 'Strategic Advisory & Compliance'), ('digital', 'Digital Systems, Automation & AI'), ('living', 'Living Systems & Regeneration')], max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#28a745', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#007bff', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy_policy_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='terms_of_service_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='strategicadvisorypagecontent',
            name='hero_image',
            field=models.URLField(default='https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop', max_length=500),
        ),
    ]
