# Generated by Django 5.2.8 on 2026-01-19 00:37

import admin_portal.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_alter_contentcard_options_alter_blogpost_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_4',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_4_title',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default),
        ),
    ]
