# Generated by Django 4.2.7 on 2025-12-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_auto_20251204_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='services_glow_image',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_1_button',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_1_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_1_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_2_button',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_2_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_3_button',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_3_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_3_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(default='Our Services', max_length=200),
        ),
    ]
