# Generated by Django 5.2.8 on 2026-01-19 00:37

import admin_portal.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_alter_contentcard_options_alter_blogpost_slug_and_more'),
    ]

    operations = [
       
    ]
