# Generated by Django 5.2.8 on 2025-12-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_add_process_description'),
        ('admin_portal', '0005_livingsystemspagecontent_and_more'),
    ]

    operations = [
    ]
