# Generated by Django 4.2.7 on 2025-12-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0006_merge_20251228_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategicadvisorypagecontent',
            name='process_step_4',
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_image_alt',
            field=models.CharField(default='Business documents and reports on a desk', max_length=200),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_description',
            field=models.TextField(default="We don't just advise — we build digital infrastructure to operationalize compliance:"),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_image_alt',
            field=models.CharField(default='Network visualization showing connected nodes and data flows', max_length=200),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_subtitle',
            field=models.CharField(default='Compliance Management', max_length=200),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_title',
            field=models.CharField(default='Digital Solutions for', max_length=200),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_who_is_this_for',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='network_cards',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='network_description',
            field=models.TextField(default='Complex compliance challenges require diverse expertise. We activate our global network of specialists to deliver comprehensive solutions.'),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='network_title',
            field=models.CharField(default='The ORR Network Advantage', max_length=200),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_1_subtitle',
            field=models.CharField(default='(Initial Discovery)', max_length=100),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_1_title',
            field=models.CharField(default='Listen & Report', max_length=100),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_2_title',
            field=models.CharField(default='Decide: Document or Partnership', max_length=100),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_3_title',
            field=models.CharField(default='Optimize (For Clients Who Continue)', max_length=100),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_subtitle',
            field=models.CharField(default='Listen . Solve . Optimize', max_length=200),
        ),
        migrations.AlterField(
            model_name='strategicadvisorypagecontent',
            name='process_step_1',
            field=models.TextField(default='We start with a focused initial meeting to understand your compliance challenges, regulatory environment, and strategic objectives.'),
        ),
        migrations.AlterField(
            model_name='strategicadvisorypagecontent',
            name='process_step_2',
            field=models.TextField(default='Once you receive the report, you choose your path forward: Use the report independently or engage ORR for ongoing implementation support.'),
        ),
        migrations.AlterField(
            model_name='strategicadvisorypagecontent',
            name='process_step_3',
            field=models.TextField(default='For clients who choose ongoing partnership, we move into implementation and optimization.'),
        ),
    ]
