# Generated by Django 5.2.8 on 2026-01-26 08:32

import admin_portal.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0006_operationalsystemspagecontent_process_step_4_and_more'),
    ]

    operations = [
    ]
