# Generated by Django 4.2.7 on 2026-01-26 06:47

import admin_portal.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0006_operationalsystemspagecontent_process_step_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_4',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_4_title',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default),
        ),
    ]
