# Generated by Django 4.2.7 on 2025-12-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0006_remove_homepage_services_glow_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services_glow_image',
            field=models.CharField(blank=True, default='/images/services_glow.png', max_length=500),
        ),
    ]
