# Generated by Django 5.2.8 on 2026-02-12 10:59

import admin_portal.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_operationalsystemspagecontent_process_step_4_and_more'),
    ]

    operations = [
       
    ]
