# Generated by Django 4.2.7 on 2025-12-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_remove_strategicadvisorypagecontent_process_step_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_image_alt',
            field=models.CharField(default='Business documents and reports on a desk', max_length=200),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_solution',
            field=models.TextField(blank=True),
        ),
    ]
