# Generated by Django 4.2.7 on 2026-03-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_operationalsystemspagecontent_process_step_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
    ]
