# Generated by Django 4.2.7 on 2025-12-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_homepage_services_glow_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestrip',
            name='user_image_1',
            field=models.CharField(default='/images/user-1.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='messagestrip',
            name='user_image_2',
            field=models.CharField(default='/images/user-2.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='messagestrip',
            name='user_image_3',
            field=models.CharField(default='/images/user-3.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='messagestrip',
            name='user_image_4',
            field=models.CharField(default='/images/user-4.jpg', max_length=500),
        ),
    ]
