# Generated by Django 4.2.7 on 2025-12-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0008_messagestrip_user_image_1_messagestrip_user_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssystemsection',
            name='card_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_systems/'),
        ),
        migrations.AlterField(
            model_name='businesssystemsection',
            name='card_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_systems/'),
        ),
        migrations.AlterField(
            model_name='businesssystemsection',
            name='card_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_systems/'),
        ),
    ]
