# Generated by Django 4.2.7 on 2025-12-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0008_operationalsystemspagecontent_case_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_image_alt',
            field=models.CharField(default='Regenerative agriculture landscape showing restored soil and biodiversity', max_length=200),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_solution',
            field=models.TextField(blank=True),
        ),
    ]
