# Generated by Django 4.2.7 on 2025-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0009_alter_businesssystemsection_card_1_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(default='About ORR Solutions', max_length=200)),
                ('hero_subtitle', models.TextField(default='Your business GP for complex systems')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_content', models.TextField(default='We help organizations thrive by optimizing their business systems')),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_content', models.TextField(default='A world where businesses operate as healthy, sustainable systems')),
                ('values_title', models.CharField(default='Our Values', max_length=200)),
                ('values_content', models.TextField(default='Integrity, innovation, and impact guide everything we do')),
                ('team_title', models.CharField(default='Our Team', max_length=200)),
                ('team_description', models.TextField(default='Meet the experts behind ORR Solutions')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(default='Get In Touch', max_length=200)),
                ('hero_subtitle', models.TextField(default="Ready to transform your business? Let's talk.")),
                ('form_title', models.CharField(default='Send us a message', max_length=200)),
                ('form_description', models.TextField(default="Fill out the form below and we'll get back to you within 24 hours")),
                ('contact_title', models.CharField(default='Contact Information', max_length=200)),
                ('office_address', models.TextField(default='123 Business Street\nSuite 100\nCity, State 12345')),
                ('phone_number', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('email_address', models.EmailField(default='hello@orrsolutions.com', max_length=254)),
                ('hours_title', models.CharField(default='Business Hours', max_length=200)),
                ('business_hours', models.TextField(default='Monday - Friday: 9:00 AM - 6:00 PM\nSaturday: 10:00 AM - 4:00 PM\nSunday: Closed')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.CreateModel(
            name='LegacyPolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(default='Legacy & Policy', max_length=200)),
                ('hero_subtitle', models.TextField(default='Our commitment to transparency and compliance')),
                ('privacy_title', models.CharField(default='Privacy Policy', max_length=200)),
                ('privacy_content', models.TextField(default='Your privacy is important to us...')),
                ('terms_title', models.CharField(default='Terms of Service', max_length=200)),
                ('terms_content', models.TextField(default='These terms govern your use of our services...')),
                ('cookies_title', models.CharField(default='Cookie Policy', max_length=200)),
                ('cookies_content', models.TextField(default='We use cookies to enhance your experience...')),
                ('compliance_title', models.CharField(default='Compliance', max_length=200)),
                ('compliance_content', models.TextField(default='We adhere to all relevant regulations...')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Legacy & Policy Page',
                'verbose_name_plural': 'Legacy & Policy Page',
            },
        ),
        migrations.CreateModel(
            name='ResourcesBlogsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(default='Resources & Insights', max_length=200)),
                ('hero_subtitle', models.TextField(default='Stay informed with our latest insights and resources')),
                ('featured_title', models.CharField(default='Featured Content', max_length=200)),
                ('featured_description', models.TextField(default='Our most popular and impactful resources')),
                ('blog_title', models.CharField(default='Latest Blog Posts', max_length=200)),
                ('blog_description', models.TextField(default='Expert insights and industry analysis')),
                ('resources_title', models.CharField(default='Downloadable Resources', max_length=200)),
                ('resources_description', models.TextField(default='Guides, templates, and tools to help your business')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resources & Blogs Page',
                'verbose_name_plural': 'Resources & Blogs Page',
            },
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(default='Our Services', max_length=200)),
                ('hero_subtitle', models.TextField(default='Comprehensive solutions for your business needs')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('strategic_title', models.CharField(default='Strategic Advisory & Compliance', max_length=200)),
                ('strategic_description', models.TextField(default='Expert guidance for strategic decisions')),
                ('strategic_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('digital_title', models.CharField(default='Digital Systems, Automation & AI', max_length=200)),
                ('digital_description', models.TextField(default='Technology solutions for modern business')),
                ('digital_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('living_title', models.CharField(default='Living Systems & Regeneration', max_length=200)),
                ('living_description', models.TextField(default='Sustainable and regenerative business practices')),
                ('living_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Services Page',
                'verbose_name_plural': 'Services Page',
            },
        ),
    ]
