# Generated by Django 4.2.7 on 2025-12-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0009_livingsystemspagecontent_case_challenge_and_more'),
    ]

    operations = [
    ]
