# Generated by Django 5.2.8 on 2025-12-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0009_alter_businesssystemsection_card_1_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
