# Generated by Django 5.2.8 on 2025-12-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0008_add_missing_strategic_advisory_fields'),
        ('admin_portal', '0010_auto_20251228_1239'),
    ]

    operations = [
    ]
