# Generated by Django 4.2.7 on 2025-12-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0010_aboutpage_contactpage_legacypolicypage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Page Content', 'verbose_name_plural': 'Contact Page Content'},
        ),
        migrations.AlterModelOptions(
            name='legacypolicypage',
            options={'verbose_name': 'Legacy & Policy Page Content', 'verbose_name_plural': 'Legacy & Policy Page Content'},
        ),
        migrations.AlterModelOptions(
            name='resourcesblogspage',
            options={'verbose_name': 'Resources & Blogs Page Content', 'verbose_name_plural': 'Resources & Blogs Page Content'},
        ),
        migrations.AlterModelOptions(
            name='servicespage',
            options={'verbose_name': 'Services Page Content', 'verbose_name_plural': 'Services Page Content'},
        ),
        migrations.RenameField(
            model_name='contactpage',
            old_name='contact_title',
            new_name='contact_info_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='form_description',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='form_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='hours_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='legacypolicypage',
            name='compliance_content',
        ),
        migrations.RemoveField(
            model_name='legacypolicypage',
            name='compliance_title',
        ),
        migrations.RemoveField(
            model_name='legacypolicypage',
            name='cookies_content',
        ),
        migrations.RemoveField(
            model_name='legacypolicypage',
            name='cookies_title',
        ),
        migrations.RemoveField(
            model_name='legacypolicypage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='legacypolicypage',
            name='privacy_content',
        ),
        migrations.RemoveField(
            model_name='legacypolicypage',
            name='privacy_title',
        ),
        migrations.RemoveField(
            model_name='legacypolicypage',
            name='terms_content',
        ),
        migrations.RemoveField(
            model_name='legacypolicypage',
            name='terms_title',
        ),
        migrations.RemoveField(
            model_name='resourcesblogspage',
            name='blog_description',
        ),
        migrations.RemoveField(
            model_name='resourcesblogspage',
            name='blog_title',
        ),
        migrations.RemoveField(
            model_name='resourcesblogspage',
            name='featured_description',
        ),
        migrations.RemoveField(
            model_name='resourcesblogspage',
            name='featured_title',
        ),
        migrations.RemoveField(
            model_name='resourcesblogspage',
            name='resources_description',
        ),
        migrations.RemoveField(
            model_name='resourcesblogspage',
            name='resources_title',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='digital_description',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='digital_image',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='digital_title',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='living_description',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='living_image',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='living_title',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='strategic_description',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='strategic_image',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='strategic_title',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address',
            field=models.TextField(default='132 Dartmouth Street Boston, Massachusetts 02156 United States'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_subtitle',
            field=models.CharField(default='Say something to start a live chat!', max_length=200),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_label',
            field=models.CharField(default='Email', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_placeholder',
            field=models.CharField(default='your@email.com', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='first_name_label',
            field=models.CharField(default='First Name', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='first_name_placeholder',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='last_name_label',
            field=models.CharField(default='Last Name', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='last_name_placeholder',
            field=models.CharField(default='Doe', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='message_label',
            field=models.CharField(default='Message', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='message_placeholder',
            field=models.CharField(default='Write your message...', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_label',
            field=models.CharField(default='Phone Number', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_placeholder',
            field=models.CharField(default='+1 012 3456 789', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_label',
            field=models.CharField(default='Select Subject?', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_1',
            field=models.CharField(default='General Inquiry', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_2',
            field=models.CharField(default='General Inquiry', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_3',
            field=models.CharField(default='General Inquiry', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_4',
            field=models.CharField(default='General Inquiry', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='submit_button_text',
            field=models.CharField(default='Send Message', max_length=50),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='hero_description',
            field=models.TextField(default='Lorem ipsm jgdu mplexity. From regulatory and sustainability frameworks to biotechnology and compliance consulting, our experts guide clients through evolving legal, scientific, and operational standards. Our approach combines deep technical insight with strategic foresight — ensuring every initiative is compliant, sustainable, and built for growth.'),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_1_description',
            field=models.TextField(default='Lorem ipsm jgdu mplexity. From regulatory and sustainability frameworks to biotechnology and compliance consulting, our experts guide clients through evolving legal, scientific, and operational standards. Our approach combines deep technical insight with strategic foresight — ensuring every initiative is compliant, sustainable, and built for growth.'),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_1_number',
            field=models.CharField(default='01', max_length=10),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_2_description',
            field=models.TextField(default='Lorem ipsm jgdu mplexity. From regulatory and sustainability frameworks to biotechnology and compliance consulting, our experts guide clients through evolving legal, scientific, and operational standards. Our approach combines deep technical insight with strategic foresight — ensuring every initiative is compliant, sustainable, and built for growth.'),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_2_number',
            field=models.CharField(default='02', max_length=10),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_3_description',
            field=models.TextField(default='Lorem ipsm jgdu mplexity. From regulatory and sustainability frameworks to biotechnology and compliance consulting, our experts guide clients through evolving legal, scientific, and operational standards. Our approach combines deep technical insight with strategic foresight — ensuring every initiative is compliant, sustainable, and built for growth.'),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_3_number',
            field=models.CharField(default='03', max_length=10),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='admin_tips_title',
            field=models.CharField(default='Admin Tips', max_length=200),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='blog_card_1_category',
            field=models.CharField(default='Article', max_length=50),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='blog_card_1_image',
            field=models.CharField(default='/images/image.png', max_length=500),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='blog_card_1_title',
            field=models.CharField(default='Mobile Apps & PWAs for Maltese Insurers: Boost Engagement | Born Digital', max_length=200),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='blog_card_2_category',
            field=models.CharField(default='Article', max_length=50),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='blog_card_2_image',
            field=models.CharField(default='/images/image.png', max_length=500),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='blog_card_2_title',
            field=models.CharField(default='Mobile Apps & PWAs for Maltese Insurers: Boost Engagement | Born Digital', max_length=200),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='blog_card_3_category',
            field=models.CharField(default='Article', max_length=50),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='blog_card_3_image',
            field=models.CharField(default='/images/image.png', max_length=500),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='blog_card_3_title',
            field=models.CharField(default='Mobile Apps & PWAs for Maltese Insurers: Boost Engagement | Born Digital', max_length=200),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='blog_card_4_category',
            field=models.CharField(default='Article', max_length=50),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='blog_card_4_image',
            field=models.CharField(default='/images/image.png', max_length=500),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='blog_card_4_title',
            field=models.CharField(default='Mobile Apps & PWAs for Maltese Insurers: Boost Engagement | Born Digital', max_length=200),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='tip_1_description',
            field=models.TextField(default='Lorem ipsum jgdu mplexity. From regulatory and sustainability frameworks to biotechnology and compliance consulting, our experts guide clients through evolving legal, scientific, and operational standards. Our approach combines deep technical insight with strategic foresight — ensuring every initiative is compliant, sustainable, and built for growth.'),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='tip_1_number',
            field=models.CharField(default='01', max_length=10),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='tip_1_title',
            field=models.CharField(default='Lorem ipsum', max_length=100),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='tip_2_description',
            field=models.TextField(default='Lorem ipsum jgdu mplexity. From regulatory and sustainability frameworks to biotechnology and compliance consulting, our experts guide clients through evolving legal, scientific, and operational standards. Our experts help clients navigate complex requirements with confidence.'),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='tip_2_number',
            field=models.CharField(default='02', max_length=10),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='tip_2_title',
            field=models.CharField(default='Lorem ipsum', max_length=100),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='tip_3_description',
            field=models.TextField(default='Lorem ipsum jgdu mplexity. From regulatory and sustainability frameworks to biotechnology and compliance consulting, our experts guide clients through evolving legal, scientific, and operational standards.'),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='tip_3_number',
            field=models.CharField(default='03', max_length=10),
        ),
        migrations.AddField(
            model_name='resourcesblogspage',
            name='tip_3_title',
            field=models.CharField(default='Lorem ipsum', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_button_text',
            field=models.CharField(default='Contact Us', max_length=50),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_description',
            field=models.TextField(default='We listen to the whole organisation, solve with structure and insight, and optimise so you can grow with confidence.'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_image',
            field=models.CharField(default='/images/handshake.png', max_length=500),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_subtitle',
            field=models.CharField(default='complex systems — digital and living.', max_length=200),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_title',
            field=models.CharField(default='ORR is your Business GP for', max_length=200),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_button_text',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_description',
            field=models.TextField(default='Insight meets adaptability. We help organizations turn data into decisions through advanced analytics, KPI dashboards, and predictive modeling. Alongside our concierge division, we offer personalized support and problem-solving — delivering smart, human solutions for both business and lifestyle needs with precision and discretion.'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_image',
            field=models.CharField(default='/man picture.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_title',
            field=models.CharField(default='Data Intelligence & Concierge Solutions', max_length=200),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_1_button_text',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_1_description',
            field=models.TextField(default='SOPs, workflows, portals, dashboards, and AI helpers that make work flow with less effort and fewer surprises.'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_1_title',
            field=models.CharField(default='Digital Systems, Automation & AI', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_2_button_text',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_2_description',
            field=models.TextField(default='Short, sharp clarity on rules, risk, and direction — from regulation and ESG to biotech and environmental questions.'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_2_title',
            field=models.CharField(default='Strategic Advisory & Compliance', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_3_button_text',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_3_description',
            field=models.TextField(default='Support for land, water, species, and ecosystems — from production systems to restoration and incident response.'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_3_title',
            field=models.CharField(default='Living Systems & Regeneration', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillars_title',
            field=models.CharField(default='The Three Pillars', max_length=200),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_button_text',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_description',
            field=models.TextField(default='We deliver clarity to complexity. From regulatory and sustainability frameworks to biotechnology and compliance consulting, our experts guide clients through evolving landscapes with confidence. Our approach combines deep technical insight with strategic foresight, ensuring every initiative is compliant, sustainable, and built for growth.'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_image',
            field=models.CharField(default='/man picture.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_title',
            field=models.CharField(default='Strategic Advisory & Compliance', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_button_text',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_description',
            field=models.TextField(default="We design, build and streamline the systems that power modern organizations. Whether it's creating SOPs, structuring onboarding workflows, or coordinating complex office setups, we turn operations into well- functioning ecosystems. Our trusted network of builders, finishers, and tech specialists delivers reliability from planning to execution."),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_image',
            field=models.CharField(default='/man picture.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_title',
            field=models.CharField(default='Operational Systems & Infrastructure', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='services_overview_title',
            field=models.CharField(default='SERVICES OVERVIEW', max_length=200),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_button_text',
            field=models.CharField(default='Sign up', max_length=50),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_description',
            field=models.TextField(default='We start simple: one calm conversation and a quick scan of your reality.'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_focus',
            field=models.TextField(default='We focus on:\n• Your context, people, and pressures\n• Regulatory, operational, data, and environmental risks\n• Which questions actually matter'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_subtitle',
            field=models.CharField(default='Listen.', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_title',
            field=models.CharField(default='STAGE 1 - DISCOVER', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_button_text',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_description',
            field=models.TextField(default='We turn symptoms into a clear map of problems and opportunities across three pillars.'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_focus',
            field=models.TextField(default='What happens here:\n• Bottleneck and process mapping\n• Compliance, governance, and risk review\n• Data and living systems scan\n• Prioritised list: urgent, high leverage, later'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_subtitle',
            field=models.CharField(default='Think. Then listen again.', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_title',
            field=models.CharField(default='STAGE 2 - DIAGNOSE', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_button_1_text',
            field=models.CharField(default='Sign up', max_length=50),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_button_2_text',
            field=models.CharField(default='Learn More on living systems & augmentation', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_description',
            field=models.TextField(default='We design practical structures not theory decks.'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_focus',
            field=models.TextField(default='Typical Outputs:\n• SOPs and standardised workflows\n• Communication and decision pathways\n• Tech stacks, integration and AI use-case\n• Simple concepts for field or nurture projects\n• Clean, structured data ready for reporting'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_subtitle',
            field=models.CharField(default='Design.', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_title',
            field=models.CharField(default='STAGE 3 - DESIGN', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_button_text',
            field=models.CharField(default='Contact Us', max_length=50),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_description',
            field=models.TextField(default='Design becomes reality with guided implementation.'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_focus',
            field=models.TextField(default='Deployment can include:\n• Admin and records setup\n• Client logging, pipeline, and follow-up flows\n• KPI fit dashboards with AI summaries\n• Staff training in the tools you already use\n• Connecting with external providers where needed'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_subtitle',
            field=models.CharField(default='Solve in practice.', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_title',
            field=models.CharField(default='STAGE 4 - DEPLOY', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_button_text',
            field=models.CharField(default='Sign up', max_length=50),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_description',
            field=models.TextField(default='Once systems are live, we keep them learning.'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_focus',
            field=models.TextField(default="How we support growth:\n• Ongoing data capture and light analytics\n• Quarterly reviews and system tuning\n• AI-assisted monitoring and early warnings\n• Scenario and 'what if' thinking\n• Light, regular check-ins — your systems clinic"),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_subtitle',
            field=models.CharField(default='Optimise.', max_length=100),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_title',
            field=models.CharField(default='STAGE 5 - GROW', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email_address',
            field=models.EmailField(default='demo@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='hero_title',
            field=models.CharField(default='Contact Us', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone_number',
            field=models.CharField(default='+012 3456 789', max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcesblogspage',
            name='hero_subtitle',
            field=models.TextField(default='Lorem ipsm ticles, practical guides, and future-focused insights on digital transformation, AI, software development, and cloud innovation, written to help your business scale with confidence.'),
        ),
        migrations.AlterField(
            model_name='resourcesblogspage',
            name='hero_title',
            field=models.CharField(default='Resources / Blogs', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='hero_subtitle',
            field=models.TextField(default='We treat your organisation as a whole system — digital, regulatory, and living. We listen first, then design the right mix of advisory, systems, AI, and on-the-ground projects so you can move better and grow smarter too.'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='hero_title',
            field=models.CharField(default='ORR Solutions - Listen. Solve. Optimise.', max_length=200),
        ),
    ]
