# Generated by Django 4.2.7 on 2025-12-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0011_delete_aboutpage_alter_contactpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('faq', 'FAQ'), ('article', 'Article'), ('checklist', 'Checklist'), ('template', 'Template'), ('guide', 'Guide'), ('announcement', 'Announcement')], max_length=20),
        ),
    ]
