# Generated by Django 5.2.8 on 2026-03-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0008_ticket_is_escalated"),
        ("admin_portal", "0011_operationalsystemspagecontent_process_step_4"),
    ]

    operations = []
