# Generated by Django 5.2.8 on 2026-04-18 22:19

import admin_portal.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0012_merge_20260303_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagecontent',
            name='contact_info_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='contact_info_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='contact_info_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='contact_info_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='email_label_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='email_label_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='email_placeholder_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='email_placeholder_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='first_name_label_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='first_name_label_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='first_name_placeholder_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='first_name_placeholder_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='hero_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='hero_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='last_name_label_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='last_name_label_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='last_name_placeholder_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='last_name_placeholder_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='message_label_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='message_label_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='message_placeholder_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='message_placeholder_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='phone_label_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='phone_label_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='phone_placeholder_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='phone_placeholder_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_label_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_label_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_option_1_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_option_1_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_option_2_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_option_2_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_option_3_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_option_3_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_option_4_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_option_4_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='submit_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='submit_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='badge_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='badge_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='button1_text_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='button1_text_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='button2_text_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='button2_text_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_content_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_content_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_subtitle_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_subtitle_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_button_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_button_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_button_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_button_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_button_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_button_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='howweoperatepagecontent',
            name='hero_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='howweoperatepagecontent',
            name='hero_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='howweoperatepagecontent',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='howweoperatepagecontent',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='howweoperatepagecontent',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='howweoperatepagecontent',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legalpolicypagecontent',
            name='hero_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legalpolicypagecontent',
            name='hero_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legalpolicypagecontent',
            name='hero_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legalpolicypagecontent',
            name='hero_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legalpolicypagecontent',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legalpolicypagecontent',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legalpolicypagecontent',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legalpolicypagecontent',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='policyitem',
            name='description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='policyitem',
            name='description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet1_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet1_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet2_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet2_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet3_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet3_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet4_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet4_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet5_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet5_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet6_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet6_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet7_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet7_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet8_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet8_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet9_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet9_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='button_text2_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='button_text2_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='button_text3_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='button_text3_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='button_text_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='button_text_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description1_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description1_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description2_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description2_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description3_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description3_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description4_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description4_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='subtitle_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='subtitle_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='wordbreak_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='wordbreak_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_button1_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_button1_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_button2_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_button2_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_description1_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_description1_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_description2_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_description2_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_description3_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_description3_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicepillar',
            name='button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicepillar',
            name='button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicepillar',
            name='description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicepillar',
            name='description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicepillar',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicepillar',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_1_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_1_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_1_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_1_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_1_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_1_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_2_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_2_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_2_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_2_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_2_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_2_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_3_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_3_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_3_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_3_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_3_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_3_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillars_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillars_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='services_overview_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='services_overview_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_focus_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_focus_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_focus_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_focus_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_button_1_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_button_1_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_button_2_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_button_2_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_focus_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_focus_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_focus_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_focus_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_focus_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_focus_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='business_gp_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='business_gp_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='business_gp_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='business_gp_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='business_gp_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='business_gp_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='business_gp_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='business_gp_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='hero_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='hero_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='hero_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='hero_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='pillars_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='pillars_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='focus_content_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='focus_content_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
    ]
