# Generated by Django 4.2.7 on 2025-12-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0012_alter_content_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='primary_pillar',
            field=models.CharField(choices=[('strategic', 'Strategic'), ('operational', 'Operational'), ('financial', 'Financial'), ('cultural', 'Cultural')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('discovery', 'Discovery'), ('consultation', 'Consultation'), ('follow_up', 'Follow Up'), ('review', 'Review')], max_length=20),
        ),
    ]
