# Generated by Django 5.2.8 on 2026-04-20 18:28

import admin_portal.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0013_contactpagecontent_contact_info_subtitle_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approachsection',
            name='paragraph_1_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='approachsection',
            name='paragraph_1_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='approachsection',
            name='paragraph_2_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='approachsection',
            name='paragraph_2_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='approachsection',
            name='paragraph_3_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='approachsection',
            name='paragraph_3_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='approachsection',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='approachsection',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemcard',
            name='description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemcard',
            name='description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemcard',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemcard',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_1_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_1_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_1_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_1_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_2_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_2_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_2_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_2_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_3_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_3_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_3_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_3_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_line1_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_line1_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_line2_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_line2_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='business_hours_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, help_text='e.g., Mon-Fri: 9AM-5PM', null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='business_hours_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, help_text='e.g., Mon-Fri: 9AM-5PM', null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='city_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='city_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='company_name_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='company_name_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='country_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='country_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='state_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='state_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_label_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_label_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_placeholder_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_placeholder_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='first_name_label_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='first_name_label_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='first_name_placeholder_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='first_name_placeholder_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='last_name_label_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='last_name_label_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='last_name_placeholder_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='last_name_placeholder_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='message_label_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='message_label_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='message_placeholder_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='message_placeholder_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_label_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_label_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_placeholder_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_placeholder_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_label_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_label_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_1_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_1_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_2_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_2_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_3_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_3_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_4_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_4_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='submit_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='submit_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='hero_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='hero_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='hero_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='hero_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_1_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_1_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_2_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_2_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_3_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_3_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='cta_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='cta_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='cta_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='cta_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='cta_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='cta_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='hero_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='hero_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='hero_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='hero_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='hero_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='hero_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_step_1_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_step_1_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_step_2_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_step_2_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_step_3_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_step_3_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_step_4_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_step_4_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_1_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_1_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_1_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_1_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_2_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_2_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_2_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_2_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_3_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_3_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_3_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_3_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='services_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='services_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='messagestrip',
            name='message_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='messagestrip',
            name='message_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='messagestrip',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='messagestrip',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='cta_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='cta_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='cta_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='cta_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='cta_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='cta_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='hero_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='hero_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='hero_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='hero_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='hero_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='hero_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_1_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_1_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_1_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_1_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_2_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_2_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_2_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_2_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_3_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_3_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_3_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_3_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_4_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_4_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_4_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_4_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_1_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_1_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_1_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_1_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_2_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_2_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_2_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_2_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_3_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_3_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_3_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_3_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='services_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='services_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_1_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_1_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_2_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_2_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_3_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_3_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_4_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_4_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrrolesection',
            name='description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrrolesection',
            name='description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrrolesection',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrrolesection',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_1_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_1_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_1_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_1_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_2_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_2_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_2_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_2_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_3_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_3_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_3_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_3_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_4_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_4_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_4_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_4_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_5_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_5_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_5_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_5_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstage',
            name='description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstage',
            name='description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstage',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstage',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='cta_button_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='cta_button_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='cta_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='cta_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='cta_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='cta_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_image_alt_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_image_alt_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='hero_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='hero_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='hero_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='hero_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='hero_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='hero_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='meta_description_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='meta_description_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='meta_title_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='meta_title_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='network_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='network_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='network_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='network_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_1_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_1_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_1_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_1_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_1_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_1_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_2_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_2_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_2_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_2_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_3_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_3_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_3_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_3_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_4_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_4_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_4_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_4_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_subtitle_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_subtitle_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_1_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_1_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_1_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_1_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_2_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_2_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_2_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_2_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_3_description_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_3_description_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_3_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_3_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='services_title_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='services_title_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_company_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_company_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_name_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_name_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_role_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_role_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_text_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_text_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
    ]
