# Generated by Django 4.2.7 on 2025-12-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0013_alter_client_primary_pillar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
