# Generated by Django 5.2.8 on 2025-12-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0010_meeting_end_datetime"),
        ("admin_portal", "0014_alter_ticket_payment_amount"),
    ]

    operations = []
