# Generated by Django 5.2.8 on 2026-04-23 13:45

import admin_portal.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0014_approachsection_paragraph_1_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approachsection',
            name='paragraph_1_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='approachsection',
            name='paragraph_2_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='approachsection',
            name='paragraph_3_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='approachsection',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemcard',
            name='description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemcard',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_1_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_1_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_2_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_2_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_3_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='card_3_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='businesssystemsection',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_line1_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_line2_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='business_hours_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, help_text='e.g., Mon-Fri: 9AM-5PM', null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='city_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='company_name_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='country_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='state_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_label_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_placeholder_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='first_name_label_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='first_name_placeholder_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='last_name_label_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='last_name_placeholder_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='message_label_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='message_placeholder_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_label_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_placeholder_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_label_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_1_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_2_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_3_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject_option_4_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='submit_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='contact_info_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='contact_info_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='email_label_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='email_placeholder_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='first_name_label_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='first_name_placeholder_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='hero_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='last_name_label_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='last_name_placeholder_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='message_label_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='message_placeholder_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='phone_label_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='phone_placeholder_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_label_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_option_1_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_option_2_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_option_3_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='subject_option_4_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='submit_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='badge_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='button1_text_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='button2_text_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_content_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_subtitle_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_button_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_1_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_button_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_2_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_button_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_3_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='howweoperatepagecontent',
            name='hero_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='howweoperatepagecontent',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='howweoperatepagecontent',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='hero_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='hero_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_1_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_2_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legacypolicypage',
            name='policy_item_3_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legalpolicypagecontent',
            name='hero_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legalpolicypagecontent',
            name='hero_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legalpolicypagecontent',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='legalpolicypagecontent',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='cta_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='cta_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='cta_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='hero_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='hero_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='hero_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_step_1_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_step_2_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_step_3_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_step_4_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='process_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_1_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_1_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_2_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_2_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_3_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='service_3_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='services_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='messagestrip',
            name='message_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='messagestrip',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='cta_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='cta_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='cta_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='hero_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='hero_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='hero_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_1_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_1_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_2_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_2_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_3_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_3_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_4_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_4_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_1_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_1_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_2_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_2_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_3_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='service_3_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='services_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_1_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_2_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_3_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='feature_4_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrreportsection',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrrolesection',
            name='description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='orrrolesection',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='policyitem',
            name='description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_1_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_1_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_2_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_2_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_3_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_3_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_4_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_4_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_5_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='stage_5_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processsection',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstage',
            name='description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstage',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet1_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet2_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet3_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet4_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet5_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet6_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet7_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet8_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='bullet9_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='button_text2_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='button_text3_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='button_text_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description1_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description2_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description3_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description4_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='subtitle_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='wordbreak_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_button1_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_button2_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_description1_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_description2_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_description3_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='hero_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='resourcesblogspagecontent',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicepillar',
            name='button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicepillar',
            name='description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicepillar',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='business_gp_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='data_intelligence_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_1_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_1_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_1_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_2_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_2_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_2_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_3_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_3_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillar_3_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='pillars_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_1_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_2_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='services_overview_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_focus_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_1_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_focus_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_2_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_button_1_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_button_2_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_focus_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_3_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_focus_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_4_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_focus_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='stage_5_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='business_gp_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='business_gp_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='business_gp_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='business_gp_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='hero_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='hero_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='pillars_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='focus_content_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='servicestage',
            name='title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='cta_button_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='cta_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='cta_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_image_alt_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='digital_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='hero_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='hero_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='hero_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='meta_description_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='meta_title_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='network_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='network_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_1_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_1_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_1_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_2_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_2_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_3_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_3_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_4_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_4_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_subtitle_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_1_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_1_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_2_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_2_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_3_description_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='service_3_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='services_title_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_company_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_name_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_role_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_text_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
    ]
