# Generated by Django 5.2.8 on 2025-12-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0015_merge_20251212_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('discovery', 'Discovery'), ('first_meeting', 'First Meeting'), ('follow_up', 'Follow Up'), ('report_review', 'Report Review')], max_length=20),
        ),
    ]
