# Generated by Django 5.2.8 on 2026-04-23 13:56

import admin_portal.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0015_approachsection_paragraph_1_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_challenge_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_challenge_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_challenge_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_image_alt_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_image_alt_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_image_alt_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_result_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_result_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_result_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_solution_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_solution_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='livingsystemspagecontent',
            name='case_solution_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_challenge_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_challenge_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_challenge_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_image_alt_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_image_alt_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_image_alt_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_result_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_result_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_result_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_solution_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_solution_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='case_solution_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_challenge_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_challenge_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_challenge_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_image_alt_ar',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_image_alt_en',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_image_alt_it',
            field=admin_portal.fields.RichTextField(default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_result_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_result_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_result_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_solution_ar',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_solution_en',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='case_solution_it',
            field=admin_portal.fields.RichTextField(blank=True, default=admin_portal.fields._default, null=True),
        ),
    ]
