# Generated by Django 4.2.30 on 2026-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0016_livingsystemspagecontent_case_challenge_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='document_source',
            field=models.CharField(choices=[('file', 'File'), ('google_doc', 'Google Doc'), ('google_sheet', 'Google Sheet')], default='file', max_length=20),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='google_drive_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
