# Generated by Django 5.2.8 on 2025-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0016_alter_meeting_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='basic_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='pain_points',
            field=models.TextField(blank=True),
        ),
    ]
