# Generated by Django 4.2.7 on 2025-12-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0015_paymentdispute_disputenote_prorataapproval_and_more'),
        ('admin_portal', '0017_meeting_basic_context_meeting_goals_and_more'),
    ]

    operations = [
    ]
