# Generated by Django 4.2.30 on 2026-05-14 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0017_clientdocument_document_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='access_rule_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='access_rule_linked_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='access_rule_type',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('payment_linked', 'Payment Linked'), ('invoice_linked', 'Invoice Linked'), ('date_linked', 'Date Linked')], default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='scan_status',
            field=models.CharField(choices=[('scanning', 'Scanning'), ('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='passed', max_length=20),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='visibility',
            field=models.CharField(choices=[('client', 'Client-Facing'), ('internal', 'Internal Only')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='client_documents/'),
        ),
        migrations.CreateModel(
            name='VaultFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('project', models.CharField(blank=True, max_length=200)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='admin_portal.client')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admin_portal.vaultfolder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='client_documents/versions/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('hash', models.CharField(blank=True, max_length=64)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='admin_portal.clientdocument')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='admin_portal.vaultfolder'),
        ),
    ]
