# Generated by Django 5.2.8 on 2025-12-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0018_merge_20251214_1220"),
        ("admin_portal", "0018_merge_20251215_1601"),
    ]

    operations = []
