# Generated by Django 5.2.8 on 2025-12-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0019_merge_20251215_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact_website',
            field=models.URLField(blank=True),
        ),
    ]
