# Generated by Django 5.2.8 on 2025-12-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0011_merge_20251228_1316"),
        ("admin_portal", "0020_ticket_contact_email_ticket_contact_name_and_more"),
    ]

    operations = []
