# Generated by Django 5.2.8 on 2026-01-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0021_merge_20251228_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcard',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='contentcard',
            name='card_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
