# Generated by Django 4.2.7 on 2026-01-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0021_merge_20251228_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationalsystemspagecontent',
            name='process_step_4',
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_1_title',
            field=models.CharField(default='Listen & Diagnose', max_length=100),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_2_title',
            field=models.CharField(default='Prescribe & Execute', max_length=100),
        ),
        migrations.AddField(
            model_name='operationalsystemspagecontent',
            name='process_step_3_title',
            field=models.CharField(default='Monitor & Optimize', max_length=100),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_4',
            field=models.TextField(default='With systems live, we provide continuous monitoring, regular reviews, and proactive adjustments to ensure your compliance strategies evolve with changing regulations and business needs.'),
        ),
        migrations.AddField(
            model_name='strategicadvisorypagecontent',
            name='process_step_4_title',
            field=models.CharField(default='Grow', max_length=100),
        ),
    ]
