# Generated by Django 4.2.7 on 2026-01-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0022_remove_operationalsystemspagecontent_process_step_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalsystemspagecontent',
            name='process_step_1_title',
            field=models.CharField(default='Listen (Assess)', max_length=100),
        ),
        migrations.AlterField(
            model_name='operationalsystemspagecontent',
            name='process_step_2_title',
            field=models.CharField(default='Solve (Design & Implement)', max_length=100),
        ),
        migrations.AlterField(
            model_name='operationalsystemspagecontent',
            name='process_step_3_title',
            field=models.CharField(default='Optimize (Refine & Evolve)', max_length=100),
        ),
    ]
