# Generated by Django 4.2.7 on 2026-01-17 12:15

from django.db import migrations
import json


def clean_rich_text_data(apps, schema_editor):
    """Clean up invalid JSON data in rich text fields"""
    
    # Get all models that have rich text fields
    models_to_clean = [
        'ApproachSection', 'BlogPost', 'BusinessSystemCard', 'BusinessSystemSection',
        'ContactInfo', 'ContactPage', 'ContactPageContent', 'ContentCard', 'FAQ',
        'HomePage', 'HowWeOperatePageContent', 'LegacyPolicyPage', 'LegalPolicyPageContent',
        'LivingSystemsPageContent', 'MessageStrip', 'OperationalSystemsPageContent',
        'ORRReportSection', 'ORRRoleSection', 'PolicyItem', 'ProcessSection',
        'ProcessStage', 'ProcessStep', 'ResourcesBlogsPage', 'ResourcesBlogsPageContent',
        'ServiceCard', 'ServicePillar', 'ServicesPage', 'ServicesPageContent',
        'ServiceStage', 'SiteSettings', 'StrategicAdvisoryPageContent', 'Testimonial'
    ]
    
    for model_name in models_to_clean:
        try:
            Model = apps.get_model('admin_portal', model_name)
            
            for instance in Model.objects.all():
                updated = False
                
                # Get all fields for this model
                for field in instance._meta.fields:
                    if hasattr(field, 'get_internal_type') and field.get_internal_type() == 'JSONField':
                        field_name = field.name
                        current_value = getattr(instance, field_name)
                        
                        if current_value is not None:
                            # If it's already a dict, ensure it has the right format
                            if isinstance(current_value, dict):
                                if 'content' not in current_value:
                                    # Convert old format to new format
                                    setattr(instance, field_name, {'content': str(current_value), 'format': 'html'})
                                    updated = True
                            elif isinstance(current_value, str):
                                # Try to parse as JSON first
                                try:
                                    parsed = json.loads(current_value)
                                    if isinstance(parsed, dict):
                                        if 'content' not in parsed:
                                            setattr(instance, field_name, {'content': str(parsed), 'format': 'html'})
                                        else:
                                            setattr(instance, field_name, parsed)
                                    else:
                                        setattr(instance, field_name, {'content': str(parsed), 'format': 'html'})
                                    updated = True
                                except (json.JSONDecodeError, ValueError):
                                    # If not valid JSON, treat as plain text
                                    setattr(instance, field_name, {'content': current_value, 'format': 'html'})
                                    updated = True
                            else:
                                # Convert any other type to string
                                setattr(instance, field_name, {'content': str(current_value), 'format': 'html'})
                                updated = True
                
                if updated:
                    instance.save()
                    
        except Exception as e:
            # Skip models that don't exist or have issues
            print(f"Skipping {model_name}: {e}")
            continue


def reverse_clean_rich_text_data(apps, schema_editor):
    """Reverse operation - not implemented as it would be destructive"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0024_fix_rich_text_data'),
    ]

    operations = [
        migrations.RunPython(clean_rich_text_data, reverse_clean_rich_text_data),
    ]