# Generated by Django 5.2.8 on 2026-01-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0022_alter_contentcard_options_contentcard_card_slug_and_more'),
        ('admin_portal', '0026_fix_rich_text_defaults'),
    ]

    operations = [
    ]
