name: CI/CD – Build & Deploy Docker Images

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate version tag
        id: vars
        run: echo "VERSION_TAG=v-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build WEB image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/orr_backend_web:latest
            ${{ secrets.DOCKER_USERNAME }}/orr_backend_web:${{ steps.vars.outputs.VERSION_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Build WORKER image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.worker
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/orr_backend_worker:latest
            ${{ secrets.DOCKER_USERNAME }}/orr_backend_worker:${{ steps.vars.outputs.VERSION_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  notify:
    needs: build
    if: failure()
    runs-on: ubuntu-latest

    steps:

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: " ORR Backend CI/CD Build FAILED"
          to: ${{ secrets.SEND_TO_EMAIL }}
          from: ${{ secrets.SMTP_USERNAME }}
          body: |
            The ORR backend CI/CD process failed.
            Branch: staging
            Workflow: Build & Deploy Docker Images
            Check logs in GitHub Actions.
